# CodeRabbit Pro Configuration for Anubis Notary
# Comprehensive security-focused review for quantum-resistant cryptographic code

language: "en-US"
tone_instructions: "Be thorough, precise, and security-focused. This is cryptographic code for a post-quantum notary system. Flag any potential security vulnerabilities, memory safety issues, or cryptographic weaknesses."

early_access: true

reviews:
  profile: "chill"
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  auto_title_placeholder: "@coderabbitai"
  review_status: true
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  poem: false
  path_filters:
    - "!**/*.lock"
    - "!**/target/**"
  path_instructions:
    - path: "crates/anubis_core/src/**/*.rs"
      instructions: |
        This is the cryptographic core of Anubis Notary. Review with EXTREME security focus:
        - Check for timing side-channel vulnerabilities (non-constant-time operations)
        - Verify all cryptographic parameters are correct (ML-DSA-87 = 4627 byte signatures, ML-KEM-1024, SHA-512 = 64 bytes)
        - Check for buffer overflows, integer overflows, and memory safety
        - Verify zeroization of sensitive data
        - Check CBOR encoding/decoding for totality and injectivity
        - Ensure no dead code, stubs, or placeholder implementations
        - Verify error handling is complete and secure
        - Check for proper input validation on all public APIs
        - Ensure RefinedRust annotations match implementation behavior
    - path: "crates/anubis_cli/src/**/*.rs"
      instructions: |
        CLI handlers for notary operations. Review for:
        - Complete implementation (no stubs or "coming soon" messages)
        - Proper error handling and user feedback
        - Input validation before calling core APIs
        - No sensitive data leakage in error messages
    - path: "neo-contract/**/*.cs"
      instructions: |
        Neo N3 smart contract for blockchain anchoring. Review for:
        - Storage key collision prevention (64-byte fingerprints hashed to 32 bytes for Neo limits)
        - Rate limiting effectiveness
        - Access control correctness (identity ownership verification)
        - Event parameter correctness
        - No reentrancy vulnerabilities
        - Integer overflow protection with BigInteger
        - Proper null checks

chat:
  auto_reply: true
